import {defineCommand} from "citty";
import {t} from "../lib/i18n";
import {withCommonArgs, runWithSdkKey, type CommonOptions} from "./_common";

type PostArgs = CommonOptions & {path?: string; data?: string; idempotencyKey?: string};
import {parseFieldArgs, resolvePathAndQuery, resolveBody} from "../lib/request-utils";

export default defineCommand({
  meta: {name: "post", description: t("cmdPost")},
  args: withCommonArgs({
    path: {type: "positional", required: true, description: t("argApiPath")},
    data: {type: "string", description: t("argRawData")},
    idempotencyKey: {
      type: "string",
      description: t("argIdempotencyKey")
    }
  }),
  run: runWithSdkKey<PostArgs>(async (ctx, args, rawArgs) => {
    const fields = parseFieldArgs(rawArgs);
    const body = await resolveBody(args.data, fields);
    const {resolvedPath, query} = resolvePathAndQuery(args.path as string, {});

    if (ctx.dryRun) {
      ctx.print({
        method: "POST",
        url: ctx.http.baseUrl + resolvedPath,
        query,
        body,
        idempotencyKey: args.idempotencyKey ?? t("idempotencyKeyAutoGenerated")
      });
      return;
    }

    const {data} = await ctx.http.request({
      method: "POST",
      path: resolvedPath,
      query,
      body,
      idempotencyKey: args.idempotencyKey
    });
    ctx.print(data);
  })
});
